# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
	
	config.vm.define "ubuntu" do |vm1|
		vm1.vm.box = "ubuntu/bionic64"
		vm1.vm.hostname = "ubuntu"
		vm1.vm.network "forwarded_port", guest: 80,  host: 8080, host_ip: "127.0.0.1"
		vm1.vm.provision :shell, path: "provision.sh"
		vm1.vm.provider "virtualbox" do |vb|
			vb.name = "ubuntu1804"
		end
	end
		
	config.vm.define "centos" do |vm2|
		vm2.vm.box = "centos/7"
		vm2.vm.hostname = "centos"
		vm2.vm.provider "virtualbox" do |vb|
			vb.name = "centos7"
		end
	end

end
