
Vagrant.configure("2") do |config|

	config.vm.define "ubuntu1804" do |vm1|
		vm1.vm.box = "ubuntu/bionic64"
		vm1.vm.hostname = "ubuntu1804"
		vm1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
		vm1.vm.synced_folder "./", "/var/www/synf"
		vm1.vm.provision :shell, path: "provision.sh"
	end
	
	config.vm.define "centos7" do |vm2|
		vm2.vm.box = "centos/7"
		vm2.vm.hostname = "centos7"
	end
end
